---
name: "Code Quality: TFLint"

on:
  push:

jobs:
  tflint:
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        examples:
          - "./examples/basic-aws"
          - "./examples/basic-azure"
          - "./examples/metrics-config-datadog"
          - "./examples/audit-log-config-datadog"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2.0.0
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          working-dir: "${{ matrix.examples }}"

      - name: Initialize TFLint
        run: tflint --init --chdir "./${{ matrix.examples }}"

      - name: Run TFLint
        run: tflint --format=compact "./${{ matrix.examples }}"
